parse_git_branch() {
  local ref
  ref=$(git symbolic-ref --quiet HEAD 2>/dev/null) || return
  printf '(%s)' "${ref##refs/heads/}"
}

update_git_segment() {
  local b
  b=$(parse_git_branch)
  if [[ -n $b ]]; then
    GIT_SEGMENT=" ${b} "
  else
    GIT_SEGMENT=" "
  fi
}

PROMPT_COMMAND=update_git_segment
PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w${GIT_SEGMENT}\$ '
