function parse_git_branch {
  local ref
  ref=$(git symbolic-ref --quiet HEAD 2>/dev/null) || return
  printf '(%s)' "${ref##refs/heads/}"
}

function update_git_segment {
  local b
  b=$(parse_git_branch)
  if [[ -n $b ]]; then
    GIT_SEGMENT=" ${b} "
  else
    GIT_SEGMENT=" "
  fi
}

PROMPT_COMMAND=update_git_segment
PS1='\u@\h:\w${GIT_SEGMENT}\$ '

alias tm="tmux new-session \; split-window -h -p 50 \; select-pane -L \; attach"
alias tm-end="tmux kill-session && clear"
