execute pathogen#infect()

syntax on
filetype plugin indent on

set tabstop=8
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab

set path+=**
set wildmenu
set wildignore+=**/*.pyc
set hidden

" have vim jump to the last position when reopening a file

autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" commits set spell and width

autocmd Filetype gitcommit setlocal spell textwidth=72

set number
set relativenumber

set background=dark
colorscheme gruvbox
