#!/usr/bin/env bash

function configure_vim() {
  mkdir -p ~/.vim/autoload ~/.vim/bundle

  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  echo -e "\nexecute pathogen#infect()" >> ~/bin/dotfiles/vimrc

  git clone https://github.com/vim-airline/vim-airline.git ~/.vim/bundle/airline
  git clone https://tpope.io/vim/fugitive.git ~/.vim/bundle/fugitive
  git clone https://github.com/mhinz/vim-signify.git ~/.vim/bundle/vim-signify
}

for WORD in $@; do
  CMD="configure_${WORD}"
  $CMD 
done
