#!/usr/bin/env bash
#
# This script will install and configure a given program.
# This script will handle a few different expected distros.
#
# Usage:
# setup COMMAND

set -e

THIS=$(realpath "$0")
HERE=$(dirname "$THIS")

source $HERE/lib/logging.sh
source $HERE/lib/utils.sh

function command_docker {
  configure_docker
}

function command_vim {
  configure_vim
}

function command_tmux {
  configure_tmux
}

function configure_help {
  log_info "The following commands can be used to configure the system:"
  local fn
  for fn in $(compgen -A function command_); do
    log_info "${fn#command_}"
  done
}

# Useful links:
# http://stackoverflow.com/questions/29581754
# https://github.com/which-distro/os-release
DISTRO_ID=$(awk -F'=' '/^ID=/ {print tolower($2)}' /etc/*-release 2> /dev/null)

source $HERE/dist-$DISTRO_ID/setup

for WORD in $@; do
  CMD="command_${WORD}"
  $CMD 
done
