#!/usr/bin/env bash
#
# The `setup` in the root directory will use these functions on arch.
# It doesn't do anything when executed directly.

THIS=$(realpath "$0")
HERE=$(dirname "$THIS")
ROOT=$(realpath "$HERE/..")

function configure_docker {
  log_info "Installing docker and docker compose v2 latest."
  sudo pacman -S docker docker-compose

  log_info "Adding $USER to docker group"
  sudo groupadd docker
  sudo usermod -aG docker $USER

  log_info "Starting and enabling docker"
  sudo systemctl enable docker --now
}

function configure_vim {
  log_info "Installing vim."
  sudo pacman -S vim

  mkdir -p ~/.vim/autoload ~/.vim/bundle

  log_info "Setting up vim addon manager (pathogen)."

  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

  log_info "Cloning vim addons."

  git clone https://github.com/vim-airline/vim-airline.git ~/.vim/bundle/airline
  git clone https://github.com/tpope/vim-fugitive.git ~/.vim/bundle/fugitive
  git clone https://github.com/mhinz/vim-signify.git ~/.vim/bundle/vim-signify
  git clone https://github.com/morhetz/gruvbox.git ~/.vim/bundle/gruvbox

  rm -f "$HOME/.vimrc"
  ln -s "$ROOT/dotfiles/vimrc" "$HOME/.vimrc"
}

function configure_tmux {
  sudo pacman -S tmux
  rm -f "$HOME/.tmux.conf"
  ln -s "$ROOT/dotfiles/tmux.conf" "$HOME/.tmux.conf"
}
