#!/usr/bin/env bash
#
# The `setup` in the root directory will use these functions on arch.
# It doesn't do anything when executed directly.

function configure_bash {
  sudo pacman -S bash-completion
  rsync -av "$HERE/dotfiles/.bashrc" "$XDG_CONFIG_HOME/.bashrc"
  rsync -av --delete "$HERE/dotfiles/.config/bashrc/" "$XDG_CONFIG_HOME/bashrc/"
}

function configure_docker {
  log_info "Installing docker and docker compose v2 latest."
  sudo pacman -S docker docker-compose

  log_info "Adding $USER to docker group"
  create_group docker
  add_user_to_group $USER docker

  log_info "Starting and enabling docker"
  sudo systemctl enable docker --now
}

function configure_vim {
  log_info "Installing vim."
  sudo pacman -S vim

  mkdir -p ~/.vim/autoload ~/.vim/bundle

  log_info "Setting up vim addon manager (pathogen)."

  curl -LSso ~/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

  log_info "Cloning vim addons."

  get_latest_git https://github.com/vim-airline/vim-airline.git ~/.vim/bundle/airline
  get_latest_git https://github.com/tpope/vim-fugitive.git ~/.vim/bundle/fugitive
  get_latest_git https://github.com/mhinz/vim-signify.git ~/.vim/bundle/vim-signify
  get_latest_git https://github.com/morhetz/gruvbox.git ~/.vim/bundle/gruvbox

  rsync -av --delete "$HERE/dotfiles/.config/vim/" "$XDG_CONFIG_HOME/vim/"
}

function configure_tmux {
  sudo pacman -S tmux
  rsync -av --delete "$HERE/dotfiles/.config/tmux/" "$XDG_CONFIG_HOME/tmux/"
}
